### PR TITLE
The one single thruth

### PR DESCRIPTION
**Pull request by eyenx**

### CODE REVIEW

**Comment by eyenx** [comment]
> it's called pineapple and it belongs on pizza

nobody asked your review.

**Comment by eyenx** [comment]
:fireworks:

**Comment by eni23** [comment]
wtf steven?

**Comment by aconitumnapellus** [comment]
> wtf steven?
Beneath this mask there is more than flesh, Beneath this mask there is an idea, Mr. Creedy, and ideas are bulletproof.

**Pull request merged**
